### ISSUE TITLE
What is Wombo ai and how to install and use 

### ISSUE THREAD

**Issue by naukarialerts4u** [ngregrichardson/wombo#1]
[Wombo ai for mac](https://www.gadgetssai.xyz/2021/12/wombo-ai-for-pc-on-windows-8107-laptop.html) 

Most of the people search this query regarding Wombo ai mac application

Because for android version we can easily install Wombo on pc using android emulators but what about mac users ?

And as I get knowledge about this Wombo ai it is freely available on iOS store so, you can easily install and use on your iPhone/ipad

Thank you

**Comment by ngregrichardson** [comment]
Hey @naukarialerts4u , I'm sorry if this project is misleading but this in no way has to do with the official Wombo.ai. This was a recreation of their original front-end app and has no actual functionality. Sorry about that!
